sudo: required
dist: trusty
language: node_js
branches:
  only:
  - master
node_js:
- '10.15'
services:
- docker
before_install:
- npm i -g npm@$(node -p "require('./package').engines.npm")
- sudo service postgresql stop
- docker-compose up -d
install:
- npm install
script:
- docker ps
- npm run test
env:
  global:
  - NODE_ENV=tests
  - DB_URI=postgres://postgres:testpassword@127.0.0.1:5433/strv-job-test-db
before_deploy: rm -rf node_modules
deploy:
  provider: heroku
  skip_cleanup: true
  app:
    master: strv-addressbook-demel-jan
  on:
    branch:
    - master
    repo: hondem/strv_job_application
    
  api_key:
    secure: RfFbpPQCJZCjaLq8JlCaZNiOjiaTq0NzaQ/dlcYUdNY13bWJqUs8OkXsUi7Cugvrtmuu7MM+ONuDoIK8pYcdD9oZ0PVXvqeHCDJz+BjxR1XC5ve5EAmxdmda3XYax/JGr5pWn2cUDGN2IAGE7gcQQJ3/8t9FZrXHVWc7XNrDj61p3O1jxtiBZRbAMMj6MkBTnxx831Idf/+11ACTnMUNPileQu597ik74TRwjQgGG9VNLuVtCHFxzJPKUM+ezZydGzdxcI2mPmAOCBKdHTyTav4k49yBzKIsCdB7yYMYeVb/LQKeMzlXhd61wzEX3HAoqhmaFku2GZB0/2d8yhmT9LXzpnwoE30bbiXYZaJKd4yKYyeOi6jOyV+CjjajJ+q82c49uyolICK8mWcE6EB3LqnHsBgtbOG1G31XmoNBUwW1OXCvWw6tWAmCd6bYCDjajhvNsA3k3QJIgJAWg2kBtv1LVINuc/ODYqcfn83zaYGXYSRyGVzR67pYhdi3b2+00N4djh2t+MJRMIQGdAt3XtPaoUc+YcDh5ZyW+oByC1VKKODuSa0NarmmPzQH+xl84xEJT9VBDEKzUTbFUYvXK5ZynnEQirTDGmk9oGawa6FP0mIZT06UuoTaFrAoULIUFRGakbahSVuj2PVvC8aZ3WBN5YQGECxZcWWdYLeyqVw=
